// setup calls
export const INIT_APP = 'INIT_APP';
export const REFRESH_APP = 'REFRESH_APP';

// Web3 lookups
export const GET_CURRENT_NETWORK = 'GET_CURRENT_NETWORK';

export const INIT_CONTRACT_DETAILS = 'INIT_CONTRACT_DETAILS';
export const REFRESH_CONTRACT_DETAILS = 'REFRESH_CONTRACT_DETAILS';
export const INIT_CROWDSALE_DETAILS = 'INIT_CROWDSALE_DETAILS';
export const REFRESH_CROWDSALE_DETAILS = 'REFRESH_CROWDSALE_DETAILS';
export const SET_STATIC_CROWDSALE_DETAILS = 'SET_STATIC_CROWDSALE_DETAILS';

export const ADD_TO_KYC_WAITING_LIST = 'ADD_TO_KYC_WAITING_LIST';
export const APPROVE_KYC = 'APPROVE_KYC';

export const PAUSE_CONTRACT = 'PAUSE_CONTRACT';
export const UNPAUSE_CONTRACT = 'UNPAUSE_CONTRACT';

export const VAULT_BALANCE = 'VAULT_BALANCE';

export const CONTRIBUTE_WEI = 'CONTRIBUTE_WEI';






