// setup calls
export const INIT_APP = 'INIT_APP';

// Web3 lookups
export const GET_CURRENT_NETWORK = 'GET_CURRENT_NETWORK';

export const REFRESH_CONTRACT_DETAILS = 'REFRESH_CONTRACT_DETAILS';
export const REFRESH_CROWDSALE_DETAILS = 'REFRESH_CROWDSALE_DETAILS';

export const ADD_TO_KYC_WAITING_LIST = 'ADD_TO_KYC_WAITING_LIST';
export const APPROVE_KYC = 'APPROVE_KYC';




