export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_CURRENT_NETWORK = 'SET_CURRENT_NETWORK';

export const SET_STATIC_CONTRACT_DETAILS = 'SET_STATIC_CONTRACT_DETAILS';
export const SET_CONTRACT_DETAILS = 'SET_CONTRACT_DETAILS';
export const SET_STATIC_CROWDSALE_DETAILS = 'SET_STATIC_CROWDSALE_DETAILS';
export const SET_CROWDSALE_DETAILS = 'SET_CROWDSALE_DETAILS';

export const SET_VAULT_BALANCE = 'SET_VAULT_BALANCE';

export const PUSH_TO_KYC_WAITING_LIST = 'PUSH_TO_KYC_WAITING_LIST';
export const REMOVE_FROM_KYC_WAITING_LIST = 'REMOVE_FROM_KYC_WAITING_LIST';


